### ISSUE TITLE
Restart needed when assay class file updated

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/dev-assay-class-api#2]
When the underlying .json file of this development server changes in GitHub, currently the server needs to be restarted to pick up the changes.  The server should just read the file (and not cache) on every call.

**Comment by yuanzhou** [comment]
Confirmed it's the Github caching:

<img width="1183" alt="Screenshot 2024-11-14 at 9 45 24 AM" src="https://github.com/user-attachments/assets/77e8781b-b80f-4e6f-be72-55d93cb51313">


Using a random query string can get the latest update immediately, but we've decided to live with the 5-minute cache.

https://github.com/user-attachments/assets/2e18bda2-9f6f-480f-8315-2d890c133f03
